---
apiVersion: {{ .Values.deployment.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: {{ .Values.deployment.strategyType}}
    {{ if eq .Values.deployment.strategyType "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.rollingUpdate.maxUnavailable }}
    {{ end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        appVersion: {{ .Chart.AppVersion }}
        helmVersion: {{ .Chart.Version }}
    spec:
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repo }}:{{ default .Chart.AppVersion .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.imagePullPolicy }}
          ports:
            - name: http-server
              containerPort: {{ .Values.deployment.containerPort }}
          env:
            - name: PORT
              value: {{ .Values.deployment.containerPort | quote }}
            - name: TEMPLATE
              value: {{ .Values.deployment.templateName }}
            - name: IDENTITY_PLATFORM_FQDN
              valueFrom:
                configMapKeyRef:
                  name: core-deployment-config
                  key: IDENTITY_PLATFORM_FQDN
            - name: IG_FQDN
              valueFrom:
                configMapKeyRef:
                  name: core-deployment-config
                  key: IG_FQDN
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
